/* SVG mockups for projects without real screenshots (IoT helmet, IoT safety, data). */
const PROJ_SVG = {
    iot_helmet: `<svg viewBox="0 0 380 240" xmlns="http://www.w3.org/2000/svg"><rect width="380" height="240" fill="#0a1628"/><defs><radialGradient id="ihg" cx="0.5" cy="0.4" r="0.6"><stop offset="0%" stop-color="rgba(34,211,238,0.35)"/><stop offset="100%" stop-color="rgba(34,211,238,0)"/></radialGradient></defs><rect width="380" height="240" fill="url(#ihg)"/><line x1="50" y1="120" x2="130" y2="120" stroke="rgba(34,211,238,0.4)" stroke-width="1.5"/><line x1="130" y1="120" x2="130" y2="65" stroke="rgba(34,211,238,0.4)" stroke-width="1.5"/><line x1="130" y1="65" x2="200" y2="65" stroke="rgba(34,211,238,0.7)" stroke-width="1.5"/><line x1="200" y1="65" x2="270" y2="120" stroke="rgba(34,211,238,0.4)" stroke-width="1.5"/><line x1="270" y1="120" x2="340" y2="120" stroke="rgba(34,211,238,0.4)" stroke-width="1.5"/><line x1="200" y1="65" x2="200" y2="170" stroke="rgba(34,211,238,0.3)" stroke-width="1.5"/><line x1="130" y1="120" x2="130" y2="170" stroke="rgba(34,211,238,0.3)" stroke-width="1.5"/><line x1="270" y1="120" x2="270" y2="170" stroke="rgba(34,211,238,0.3)" stroke-width="1.5"/><circle cx="50"  cy="120" r="6" fill="rgba(34,211,238,0.9)"/><circle cx="130" cy="120" r="10" fill="rgba(34,211,238,0.15)" stroke="rgba(34,211,238,0.85)" stroke-width="1.5"/><circle cx="200" cy="65"  r="14" fill="rgba(34,211,238,0.18)" stroke="rgba(34,211,238,1)" stroke-width="2"/><circle cx="270" cy="120" r="10" fill="rgba(34,211,238,0.15)" stroke="rgba(34,211,238,0.85)" stroke-width="1.5"/><circle cx="340" cy="120" r="6" fill="rgba(34,211,238,0.75)"/><circle cx="130" cy="170" r="5" fill="rgba(34,211,238,0.55)"/><circle cx="200" cy="170" r="5" fill="rgba(34,211,238,0.55)"/><circle cx="270" cy="170" r="5" fill="rgba(34,211,238,0.55)"/><text x="186" y="60" fill="rgba(34,211,238,0.95)" font-size="9" font-family="monospace" font-weight="600">GPS</text><path d="M324 102 Q333 90 342 102" stroke="rgba(34,211,238,0.65)" fill="none" stroke-width="1.6" stroke-linecap="round"/><path d="M318 93  Q333 76 348 93"  stroke="rgba(34,211,238,0.4)"  fill="none" stroke-width="1.6" stroke-linecap="round"/><rect x="18" y="14" width="120" height="24" rx="4" fill="rgba(34,211,238,0.10)" stroke="rgba(34,211,238,0.25)"/><text x="28" y="30" fill="rgba(34,211,238,0.7)" font-size="10" font-family="monospace">ALCOHOL + GPS</text></svg>`,
    iot_safety: `<svg viewBox="0 0 380 240" xmlns="http://www.w3.org/2000/svg"><rect width="380" height="240" fill="#0d1117"/><rect x="173" y="18" width="14" height="200" fill="rgba(255,255,255,0.05)" rx="3"/><rect x="152" y="32" width="56" height="120" rx="9" fill="rgba(17,24,39,0.95)" stroke="rgba(255,255,255,0.12)" stroke-width="1"/><circle cx="180" cy="60" r="16" fill="rgba(239,68,68,0.92)"/><circle cx="180" cy="60" r="22" fill="rgba(239,68,68,0.18)"/><circle cx="180" cy="98" r="16" fill="rgba(255,255,255,0.06)"/><circle cx="180" cy="138" r="16" fill="rgba(34,197,94,0.12)"/><rect x="50" y="156" width="64" height="38" rx="4" fill="rgba(248,250,252,0.9)"/><rect x="50" y="156" width="16" height="38" rx="4" fill="rgba(239,68,68,0.85)"/><circle cx="66" cy="198" r="8" fill="rgba(30,30,30,0.9)"/><circle cx="96" cy="198" r="8" fill="rgba(30,30,30,0.9)"/><text x="76" y="180" fill="rgba(239,68,68,0.95)" font-size="12" font-family="monospace" font-weight="bold">+</text><rect x="252" y="106" width="86" height="46" rx="5" fill="rgba(17,24,39,0.75)" stroke="rgba(99,102,241,0.45)" stroke-width="1"/><text x="262" y="128" fill="rgba(129,140,248,0.85)" font-size="9" font-family="monospace">ULTRASONIC</text><text x="262" y="142" fill="rgba(129,140,248,0.65)" font-size="8" font-family="monospace">BLIND SPOT</text><line x1="208" y1="128" x2="252" y2="128" stroke="rgba(99,102,241,0.4)" stroke-dasharray="5 3"/><rect x="18" y="14" width="135" height="24" rx="4" fill="rgba(99,102,241,0.08)" stroke="rgba(99,102,241,0.2)"/><text x="28" y="30" fill="rgba(129,140,248,0.7)" font-size="10" font-family="monospace">SAFETY SYSTEMS</text></svg>`,
    analytics:  `<svg viewBox="0 0 380 240" xmlns="http://www.w3.org/2000/svg"><rect width="380" height="240" fill="#0d1b2a"/><line x1="0" y1="190" x2="380" y2="190" stroke="rgba(255,255,255,0.07)" stroke-dasharray="4 4"/><line x1="0" y1="140" x2="380" y2="140" stroke="rgba(255,255,255,0.07)" stroke-dasharray="4 4"/><line x1="0" y1="90"  x2="380" y2="90"  stroke="rgba(255,255,255,0.07)" stroke-dasharray="4 4"/><rect x="32"  y="120" width="38" height="68"  fill="rgba(8,145,178,0.55)"  rx="3"/><rect x="92"  y="78"  width="38" height="110" fill="rgba(8,145,178,0.75)"  rx="3"/><rect x="152" y="98"  width="38" height="90"  fill="rgba(8,145,178,0.62)"  rx="3"/><rect x="212" y="58"  width="38" height="130" fill="rgba(14,165,233,0.85)" rx="3"/><rect x="272" y="82"  width="38" height="106" fill="rgba(8,145,178,0.68)"  rx="3"/><rect x="332" y="68"  width="38" height="120" fill="rgba(8,145,178,0.78)"  rx="3"/><polyline points="50,128 110,82 170,102 230,68 290,90 350,72" stroke="#22d3ee" stroke-width="2.4" fill="none" stroke-linecap="round" stroke-linejoin="round"/><circle cx="50"  cy="128" r="4" fill="#22d3ee"/><circle cx="110" cy="82"  r="4" fill="#22d3ee"/><circle cx="170" cy="102" r="4" fill="#22d3ee"/><circle cx="230" cy="68"  r="4" fill="#22d3ee"/><circle cx="290" cy="90"  r="4" fill="#22d3ee"/><circle cx="350" cy="72"  r="4" fill="#22d3ee"/><rect x="18" y="14" width="120" height="26" rx="5" fill="rgba(255,255,255,0.05)"/><text x="30" y="32" fill="rgba(255,255,255,0.55)" font-size="11" font-family="monospace">POWER BI</text></svg>`,
};

const DATA = {
    en: {
        nav_about: "About",
        nav_services: "What I Do",
        nav_projects: "Projects",
        nav_contact: "Contact",
        marquee_h2: "Selected Work",
        hero_taglines: [
            "building 7-phase CO₂ capture sims in Unity",
            "shipping SwiftUI apps for 55+ tickers",
            "training adaptive-learning LLMs at OVGU",
            "open to Werkstudent roles — Q2 2026",
            "backend · iOS · simulation · all of it"
        ],
        btn_get_in_touch: "Get In Touch",
        h3_status: "OPEN · WORKING STUDENT · MAGDEBURG / REMOTE · Q2 2026",
        h3_sub: "M.Sc. Digital Engineering / OVGU Magdeburg",
        h3_pitch: "I build backend systems, real-time simulations, and native iOS — end to end.",
        h3_about: "M.Sc. Digital Engineering student at OVGU Magdeburg building backend systems, SwiftUI apps, and interactive simulations. I am seeking a working-student role in Germany starting Q2 2026.",
        cta_sim: "Run simulation",
        cta_resume: "Résumé.pdf",
        cta_contact: "Contact",
        badge_cap: "ID · MAGDEBURG · DE",
        proof_python: "LLM evaluation pipeline in HCAI project",
        proof_javascript: "This portfolio — vanilla, zero frameworks",
        proof_csharp: "Unity CO₂ control & system physics scripts",
        proof_swift: "StockWatch — native iOS app, 55+ tickers",
        proof_sql: "Relational database schema for HCAI tutor",
        proof_bash: "Automation scripts, file cleanup pipelines",
        proof_unity: "7-phase CO₂ simulation, live on Unity Play",
        proof_swiftui: "StockWatch charts, lists & settings dashboard",
        proof_gsap: "Pinned scrollytelling + the CO₂ scrub",
        proof_llms: "AI adaptive learning system (Gemini/Llama)",
        proof_langchain: "LLM agent workflow in HCAI tutor project",
        proof_huggingface: "Transformers + model evaluation, HCAI project",
        proof_prompteng: "Chain-of-Thought + guardrails, HCAI project",
        proof_restjson: "Live market data endpoints in StockWatch",
        proof_git: "Strict branch management across all project repos",
        proof_cicd: "GitHub Actions setup for static deployments",
        proof_xctest: "StockWatch persistence + math unit test suite",
        proof_figma: "UI mockups + design tokens for StockWatch",
        proof_blender: "6 detailed plant models for CO₂ simulation",
        sim_static_stage01: "STAGE 01",
        sim_static_title01: "Flue gas in",
        sim_static_desc01: "Grey flue-gas stream enters the absorber at CO₂ ≈ 12.4%.",
        sim_static_stage02: "STAGE 02",
        sim_static_title02: "Absorber",
        sim_static_desc02: "Particles meet the solvent stream and are captured — capture rate climbs toward 95%.",
        sim_static_stage03: "STAGE 03",
        sim_static_title03: "Desorber",
        sim_static_desc03: "Amber heat releases a pure CO₂ stream upward — purity exceeds 95%.",
        sim_static_stage04: "STAGE 04",
        sim_static_title04: "Output",
        sim_static_desc04: "Compressed CO₂ exits. Built as a 7-phase Unity coroutine with Blender models in C#.",
        sim_eyebrow: "The Simulation",
        sim_intro: "A seven-phase Unity model of industrial post-combustion CO₂ capture for a 1000 MW reference plant. Scroll to run it.",
        sim_cta_build: "Play the WebGL build",
        sim_cta_case: "Read case study",
        systems_eyebrow: "Selected Systems",
        stack_eyebrow2: "The Stack",
        stack_proof_hint: "Every cell names where I actually used it.",
        traj_eyebrow: "Trajectory",
        hand_eyebrow: "Let's connect",
        hand_intro: "Open to working-student roles from Q2 2026 — hybrid or remote, Germany. Tell me what you're building.",
        copy_done: "Copied",
        footer_tagline: "Backend systems, real-time simulation, and native iOS — built end to end.",
        heatmap_title: "GitHub activity",
        heatmap_hint: "illustrative · open profile for live graph →",

        /* ---- v2: nav (9 sections) ---- */
        nav_identity: "Identity",
        nav_simulation: "Simulation",
        nav_systems: "Systems",
        nav_capabilities: "Capabilities",
        nav_stack: "Stack",
        nav_trajectory: "Trajectory",
        nav_now: "Now",

        /* ---- v2: hero ProfileCard ---- */
        pc_role: "Backend · iOS · Simulation Developer",
        pc_status: "Open to work",
        pc_contact: "Contact me",

        /* ---- v2: About section ---- */
        ab_stats: [
            { n: 5,    suf: "",  lbl: "projects shipped" },
            { n: 7,    suf: "",  lbl: "Unity simulation phases" },
            { n: 55,   suf: "+", lbl: "live tickers · 5 exchanges" },
            { n: 1000, suf: "+", lbl: "participants led · VITOPIA 2024" }
        ],
        ab_sign: "Working with curiosity, shipping with proof.",
        idcard_hint: "Drag the card in any direction and release — it drops and swings on its lanyard.",

        /* ---- v2: NOW (currently building) ---- */
        now_h2: "Now Building",
        now_intro: "Live processes — what is running right now.",
        now_p1_name: "HCAI · Adaptive Learning Pathway System",
        now_p1_desc: "LLM-driven tutor with Chain-of-Thought prompting and LLM-as-Judge bias evaluation. Gemini + local Llama 3 via Ollama, LangChain, Guardrails AI. 4-person OVGU team — paper due July 2026.",
        now_p1_status: "RUNNING",
        now_p2_name: "This portfolio",
        now_p2_desc: "Hand-built vanilla JS instrument panel — GSAP + Lenis scroll engine, bilingual EN/DE, dual theme, zero frameworks.",
        now_p2_status: "LIVE",

        /* ---- v2: command palette (⌘K) ---- */
        cmdk_placeholder: "Jump to section, switch theme, copy email…",
        cmdk_empty: "No matches",
        cmdk_group_nav: "Navigate",
        cmdk_group_docs: "Documents",
        cmdk_group_links: "Links",
        cmdk_group_act: "Actions",
        cmdk_theme: "Switch theme",
        cmdk_lang: "Auf Deutsch wechseln",
        cmdk_copy: "Copy email address",
        cmdk_cv: "Download CV (PDF)",
        cmdk_cv_en: "Download CV — English (PDF)",
        cmdk_cv_de: "Download CV — German (PDF)",
        cmdk_case: "Read the CO₂ simulation case study",
        cmdk_unity: "Play the CO₂ simulation (Unity build)",
        cmdk_stockwatch: "StockWatch — iOS app repo (GitHub)",
        cmdk_now: "Open /now — what I'm building",
        cmdk_uses: "Open /uses — my toolkit",
        cmdk_github: "Open GitHub profile",
        cmdk_linkedin: "Open LinkedIn profile",
        cmdk_results: "results",
        cmdk_result: "result",
        cmdk_hint_nav: "navigate",
        cmdk_hint_sel: "select",
        cmdk_hint_close: "close",

        /* ---- v2: mobile drawer + share ---- */
        drawer_title: "Menu",
        share_btn: "Share this portfolio",
        share_ok: "Link copied",

        /* ---- v2: localized aria labels (data-i18n-attr) ---- */
        a11y_chapters: "Chapters",
        a11y_close_menu: "Close menu",
        a11y_open_menu: "Open menu",
        a11y_cmdk_label: "Command palette",
        a11y_cmdk_open: "Open command menu (Ctrl+K or Command+K)",
        a11y_idcard: "Hashwanth Ghanta — M.Sc. Digital Engineering student ID, OVGU Magdeburg",
        a11y_heatmap: "GitHub activity — open my GitHub profile to see the real contribution graph (opens in new tab)",
        rail_01: "01 — Identity",
        rail_02: "02 — About",
        rail_03: "03 — Simulation",
        rail_04: "04 — Systems",
        rail_05: "05 — Capabilities",
        rail_06: "06 — Stack",
        rail_07: "07 — Trajectory",
        rail_08: "08 — Now building",
        rail_09: "09 — Contact",
        ann_lang: "Language: English",
        ann_theme_dark: "Dark theme on",
        ann_theme_light: "Light theme on",
        a11y_sections: "Sections",
        a11y_language: "Language",
        a11y_secondary: "Secondary",
        a11y_social: "Social",
        a11y_back_top: "Back to top",
        a11y_commands: "Commands",
        a11y_profilecard: "Profile card",
        a11y_studentid_mount: "Student ID card",
        a11y_copy_email: "Copy email address",
        a11y_copy_linkedin: "Copy LinkedIn URL",
        a11y_copy_github: "Copy GitHub URL",
        a11y_coursework: "Coursework",
        a11y_theme_to_light: "Switch to light theme",
        a11y_theme_to_dark: "Switch to dark theme",
        cursor_drag: "DRAG",
        skills_eyebrow: "Proof, not self-ratings",
        skills_h2: "Skills",
        track_eyebrow: "Track Record",
        track_h2: "Shipped & Led",
        edu_eyebrow: "Studied",
        education_h2: "Where I Studied",
        nav_skills: "Skills",
        nav_track: "Experience",
        nav_education: "Education",
        cf_heading: "Send a message",
        ct_location: "Location",
        about_h2:  "About Me",
        about_text:"I'm an M.Sc. Digital Engineering student at OVGU Magdeburg focused on backend, simulation, and iOS. I ship things end-to-end — Unity 3D simulations in C#, native SwiftUI apps with live finance data, IoT prototypes on Arduino. I care about clean code, measurable outcomes, and the boring details that make software actually work.",
        stat_phases:"Unity simulation phases shipped",
        stat_projects:"Live stock tickers across 5 exchanges",
        stat_available:"Participants led at VITOPIA 2024",
        creds_avail_lbl:"Availability",
        creds_avail_val:"Working student from Q2 2026 · hybrid or remote, Germany · eligible for Werkstudent roles",
        creds_status_lbl:"Work status",
        creds_status_val:"Enrolled student in Germany — eligible for Werkstudent roles",
        creds_lang_lbl:"Languages",
        creds_lang_val:"English (fluent) · German A2 (enrolled at OVGU)",
        services_h2:"What I Do",
        projects_h2:"Projects",
        contact_h2:"Let's Connect",
        contact_lede:"Available Q2 2026 for working-student roles — backend, frontend, data engineering, analytics, databases, iOS, simulation, or any tech domain. Hybrid or remote, Germany. Fastest reply: email.",
        ct_email:"Email", ct_linkedin:"LinkedIn", ct_github:"GitHub",
        cf_name:"Your name", cf_email:"Your email", cf_msg:"Message",
        btn_send:"Send Message",
        live: "Live Project",
        details: "Details",
        cf_ok: "Message sent. I will get back to you soon.",
        cf_err: "Something went wrong — please email me directly.",
        heroChips: ["C#", "SQL", "Python", "Swift", "SwiftUI", "Xcode", "JavaScript", "GitHub", "Unity 3D", "Blender"],
        skillsGroups: [
            { category: "3D & Simulation",
              proofs: [
                  { name: "Unity 3D", note: "7-phase CO₂ capture simulation", href: "#project-01" },
                  { name: "C# (Unity)", note: "Modular manager architecture across simulation phases", href: "#project-01" },
                  { name: "TextMeshPro / URP", note: "Custom in-engine UI for parameter sliders", href: "#project-01" },
              ],
              chips: ["Unity 3D", "C#", "TextMeshPro", "URP", "3D Modeling", "Simulation Design"] },
            { category: "Backend & Programming",
              proofs: [
                  { name: "Python", note: "Data prep + ad-hoc pipelines (analytics projects)", href: "#project-05" },
                  { name: "SQL", note: "OVGU Database Concepts coursework + analytics", href: "#education" },
                  { name: "Swift / SwiftUI", note: "StockWatch iOS app, MVVM + async/await", href: "https://github.com/hashwanthghanta/stockwatch-ios" },
                  { name: "JavaScript", note: "This portfolio — vanilla JS, no framework", href: "https://github.com/hashwanthghanta/hashwanthghanta.github.io" },
              ],
              chips: ["Python", "SQL", "JavaScript", "Swift", "SwiftUI", "C (Arduino)"] },
            { category: "Tools & Platforms",
              proofs: [
                  { name: "Git / GitHub", note: "Public repos for portfolio + StockWatch", href: "https://github.com/hashwanthghanta" },
                  { name: "Arduino / Raspberry Pi", note: "IoT helmet + ambulance-priority controller", href: "#project-03" },
              ],
              chips: ["Git", "GitHub", "Jira", "SAP", "Arduino", "Raspberry Pi"] },
            { category: "Currently learning (2025–26)",
              proofs: [
                  { name: "LLMs / Hugging Face", note: "Building a small RAG demo over my own projects", href: "#projects" },
                  { name: "Prompt engineering", note: "Used daily for pair-programming, code review, and refactors", href: "#projects" },
              ],
              chips: ["LLMs", "Hugging Face", "Prompt Engineering", "Transformers", "AI/ML Concepts"] },
            { category: "Editing & Visualization",
              proofs: [
                  { name: "Premiere Pro", note: "Edited the CO₂ simulation walkthrough", href: "#project-01" },
                  { name: "Blender", note: "Modelling six engineering-accurate 3D plant components", href: "#project-01" },
              ],
              chips: ["Adobe", "Videography", "Animation", "Colour Grading", "3D Modeling"] },
            { category: "Data & Analytics",
              proofs: [
                  { name: "Power BI", note: "Tata Data Visualization certification dashboards", href: "#project-05" },
                  { name: "Excel", note: "Microsoft Business Analysis + financial modelling", href: "#project-05" },
              ],
              chips: ["Power BI", "Excel", "Data Visualization", "Business Analytics"] },
        ],
        track: [
            { date: "2025 – Present", role: "Simulation Coursework & Lab Projects", org: "OVGU Magdeburg · Digital Engineering",
              body: "Built Unity simulations, C# system architecture, and interactive UI workflows across lab modules in industrial systems and visualization." },
            { date: "2025 – Present", role: "Web Development — Portfolio & Case Studies", org: "Personal Project",
              body: "Designed and shipped a bilingual portfolio with project case studies, accessibility improvements, and performance-first UI." },
            { date: "2024", role: "Volunteer Head — VITOPIA 2024", org: "VIT-AP University Annual Cultural Festival, India",
              body: "Managed the largest annual college event with 1,000+ participants including students and celebrity guests. Coordinated logistics, student teams, event scheduling, and live activity management across cultural and technical events." },
        ],
        education: [
            { iconKey: "grad", degree: "M.Sc. Digital Engineering", period: "April 2025 – Present",
              detail: "<strong>OVGU, Magdeburg, Germany</strong>",
              focusAreasLabel: "Focus areas",
              focusAreas: ["Digital systems", "Simulation", "Software engineering", "Data science"],
              subjectsLabel: "Coursework",
              subjects: [
                  { name: "DE visualization project", focus: true },
                  { name: "Database concepts" },
                  { name: "Data mining" },
                  { name: "AI best decision support" },
                  { name: "Introduction to computer science engineering" },
              ] },
            { iconKey: "zap", degree: "B.Tech Electronics & Communication", period: "2020 – 2024",
              detail: "<strong>VIT-AP University, India</strong><br>CGPA 7.72 / 10.0",
              focusAreasLabel: "Focus areas",
              focusAreas: ["IoT", "Embedded systems", "Wireless communication"] },
            { iconKey: "award", degree: "Certifications", period: "2023 – 2024",
              badges: ["Data Visualization – Tata","Business Analysis – Microsoft","Business Analytics – Coursera","IoT Cloud Computing – Coursera","IoT Programming with Boards – Coursera","Project Management – Coursera","Power BI Workshop"] },
        ],
        services: [
            { name: "Software & Backend Development",       desc: "Clean object-oriented programming (OOP) in C# and Swift, robust backend architecture, database integration (SQL), and optimized logic implementation." },
            { name: "iOS & SwiftUI Development",    desc: "Native iOS apps in SwiftUI with MVVM, async/await networking, interactive Swift Charts, and full English + German localization." },
            { name: "Data Visualization & Analytics", desc: "Power BI dashboards, Excel models, and Python pipelines that turn raw operational data into clear KPIs, trends, and decision support." },
            { name: "IoT & Embedded Systems",       desc: "Arduino and microcontroller systems for safety-critical use cases — smart helmets, ambulance signalling, ultrasonic blind-spot detection." },
            { name: "Web & Brand Design",           desc: "Bilingual portfolios and case-study sites with accessible markup, performance-first UI, and clear visual identity." },
        ],
        projects: [
            {
                num: "01",
                cat: "Featured · Unity 3D + Blender",
                name: "Post-Combustion CO₂ Carbon Capture Simulation",
                period: "2025 – 2026",
                desc: "Five-person OVGU Magdeburg team project simulating industrial post-combustion CO₂ capture for a 1000 MW reference plant. My role: Unity & Blender Developer. Six engineering-accurate 3D models in Blender 4.x, a seven-phase Unity coroutine in C#, two live temperature sliders driving particle systems and the efficiency graph.",
                highlights: [
                    "5-person collaboration across Digital + Chemical Engineering at OVGU Magdeburg",
                    "Two live temperature sliders — absorber 0–65°C and stripper 75–125°C — drive particle colour, density, and the efficiency graph in real time",
                    "Six engineering-accurate 3D models (absorber, stripper, reboiler, heat exchanger, compressor, CO₂ storage tank) modelled in Blender 4.x, exported to Unity via FBX",
                    "11 C# scripts on a Singleton + partial-ECS pattern; overheat watchdog stops everything at 125°C",
                    "Playable live on Unity Play — no install",
                ],
                learned: "Apply Transform on FBX export is non-negotiable — Blender's Z-up world arrives in Unity's Y-up scene rotated 90° and scaled 1/100 without it. One checkbox saved a week of debugging the asset pipeline.",
                tags: ["Unity 2022 LTS", "C#", "Blender 4.x", "TextMeshPro", "UI Toolkit", "FBX pipeline", "Simulation"],
                url:  "https://play.unity.com/en/games/30f22392-532c-41e1-b925-6191a9ea99c2/post-combustion-co-carbon-capture",
                urlLabel: "Open Live Demo",
                caseStudy: "projects/co2-simulation.html",
                caseStudyLabel: "Read case study",
                img1: "Images/co2-simulation.webp",
                img2: "Images/co2-preview.jpg",
            },
            {
                num: "02",
                cat: "Open Source · iOS · SwiftUI",
                name: "StockWatch — SwiftUI Watchlist for iOS",
                period: "2026",
                desc: "Native iOS watchlist app inspired by Scalable Capital. Live Yahoo Finance quotes, 55+ tickers across US, German Xetra, UK, Swiss and Danish exchanges, list + grid layouts, interactive Swift Charts with seven time ranges, symbol-relevant news, EN/DE runtime language switch, Dark/Light/System theming.",
                highlights: [
                    "Interactive Swift Charts detail view — scrub the line to inspect closing price and date",
                    "MVVM with @MainActor @Observable, protocol-based DI, async/await + URLSession",
                    "Runtime English / German language switch via Bundle swizzling",
                    "XCTest suite covering persistence, refresh transitions, and percent-change math",
                ],
                learned: "Protocol-based DI + @MainActor @Observable made the XCTest suite trivial — I swapped a fake Yahoo client into the ViewModel without touching production code paths.",
                tags: ["Swift", "SwiftUI", "Swift Charts", "async/await", "MVVM", "XCTest", "iOS 17+"],
                url:  "https://github.com/hashwanthghanta/stockwatch-ios",
                urlLabel: "View on GitHub",
                caseStudy: "projects/stockwatch.html",
                caseStudyLabel: "Read case study",
                img1: "Images/stockwatch-thumb-sm.jpg",
                img2: "Images/v6_grid_dark-sm.jpg",
            },
            {
                num: "03",
                cat: "IoT · Arduino",
                name: "IoT Smart Helmet & Bike Safety System",
                period: "2024",
                desc: "GPS and alcohol-sensor-equipped smart helmet that detects unsafe riding conditions and auto-alerts emergency contacts. Built to reduce motorcycle fatalities through real-time monitoring and automated safety enforcement.",
                highlights: [
                    "GPS module + alcohol sensor on Arduino-class microcontroller",
                    "Automated emergency-contact alerting on unsafe-condition detection",
                    "Field-tested wearable form factor",
                ],
                learned: "Software-only gates are theatre — the ignition only stays locked because the relay is physically in series with the starter. Calibrate the MQ-3 in firmware setup, not at the bench, or the first demo fails.",
                tags: ["NodeMCU", "ATmega328P", "FSR", "MQ-3", "GSM", "GPS", "Embedded C"],
                svg: "iot_helmet",
                caseStudy: "projects/iot-helmet.html",
                caseStudyLabel: "Read case study",
            },
            {
                num: "04",
                cat: "IoT · Embedded · B.Tech",
                name: "IoT Safety Systems — Traffic & Vehicle",
                period: "2022 – 2023",
                desc: "Two embedded-systems projects from B.Tech coursework: a traffic-junction controller that gives ambulances signal priority, and an ultrasonic blind-spot detector for vehicles. Both built on Arduino and microcontroller platforms with embedded C.",
                highlights: [
                    "Ambulance-priority traffic junction controller — RF + microcontroller",
                    "Ultrasonic blind-spot detector with audible/visual driver alerts",
                    "Embedded C on Arduino-class hardware",
                ],
                learned: "Two safety devices, one lesson: an alert nobody hears is no alert. The ultrasonic blind-spot tone had to be tuned around engine noise — taught me to design feedback for the real environment, not the bench.",
                tags: ["IoT", "Arduino", "Sensors", "Embedded C"],
                svg: "iot_safety",
            },
            {
                num: "05",
                cat: "Data · Analytics · BI",
                name: "Data Analytics & Business Intelligence Dashboards",
                period: "2023 – 2024",
                desc: "Power BI dashboards and Excel models built for business data analysis as part of certification work with Tata and Microsoft. Applied data visualization principles to surface KPIs, trends, and operational insights for non-technical stakeholders.",
                highlights: [
                    "Power BI dashboards translating operational data into KPI views",
                    "Excel financial / forecasting models with named-range refactoring",
                    "Python pipelines for data prep and ad-hoc analysis",
                ],
                learned: "Non-technical stakeholders read a dashboard the way a developer reads a stack trace — top-down, hunting for the one number that's wrong. I now design dashboards with the headline number first, drill-down second.",
                tags: ["Power BI", "Excel", "Data Visualization", "Business Analytics", "Python"],
                svg: "analytics",
            },
        ],
    },
    de: {
        nav_about: "Über mich",
        nav_contact: "Kontakt",
        hero_taglines: [
            "baue 7-phasige CO₂-Abscheidungssimulationen in Unity",
            "entwickle SwiftUI-Apps für 55+ Aktien",
            "trainiere adaptive Lern-LLMs an der OVGU",
            "offen für Werkstudentenstellen — Q2 2026",
            "Backend · iOS · Simulation · alles davon"
        ],
        btn_get_in_touch: "Kontakt aufnehmen",
        h3_status: "OFFEN · WERKSTUDENT · MAGDEBURG / REMOTE · Q2 2026",
        h3_sub: "M.Sc. Digital Engineering / OVGU Magdeburg",
        h3_pitch: "Ich baue Backend-Systeme, Echtzeit-Simulationen und native iOS-Apps — von Anfang bis Ende.",
        h3_about: "M.Sc.-Student Digital Engineering an der OVGU Magdeburg mit Fokus auf Backend-Systeme, SwiftUI-Apps und interaktive Simulationen. Ich suche eine Werkstudentenstelle in Deutschland ab Q2 2026.",
        cta_sim: "Simulation starten",
        cta_resume: "Lebenslauf.pdf",
        cta_contact: "Kontakt",
        badge_cap: "ID · MAGDEBURG · DE",
        proof_python: "LLM-Evaluation-Pipeline im HCAI-Projekt",
        proof_javascript: "Dieses Portfolio — vanilla, kein Framework",
        proof_csharp: "Unity-CO₂-Steuerungs- & Systemphysik-Skripte",
        proof_swift: "StockWatch — native iOS-App, 55+ Ticker",
        proof_sql: "Relationales Datenbankschema für HCAI-Tutor",
        proof_bash: "Automationsskripte, Bereinigungspipelines",
        proof_unity: "7-Phasen-CO₂-Simulation, live auf Unity Play",
        proof_swiftui: "StockWatch Charts, Listen & Einstellungs-Dashboard",
        proof_gsap: "Gepinntes Scrollytelling + CO₂-Scrub",
        proof_llms: "Adaptives KI-Lernsystem (Gemini/Llama)",
        proof_langchain: "LLM-Agenten-Workflow im HCAI-Tutor-Projekt",
        proof_huggingface: "Transformers + Modellbewertung, HCAI-Projekt",
        proof_prompteng: "Chain-of-Thought + Guardrails, HCAI-Projekt",
        proof_restjson: "Live-Marktdaten-Endpunkte in StockWatch",
        proof_git: "Strikte Branch-Verwaltung in allen Projekt-Repos",
        proof_cicd: "GitHub-Actions-Setup für statische Deployments",
        proof_xctest: "StockWatch-Persistenz- + Mathe-Unit-Tests",
        proof_figma: "UI-Mockups + Design-Tokens für StockWatch",
        proof_blender: "6 detaillierte Anlagenmodelle für CO₂-Simulation",
        sim_static_stage01: "STUFE 01",
        sim_static_title01: "Rauchgaszufuhr",
        sim_static_desc01: "Grauer Rauchgasstrom tritt mit einem CO₂-Gehalt von ca. 12,4 % in den Absorber ein.",
        sim_static_stage02: "STUFE 02",
        sim_static_title02: "Absorber",
        sim_static_desc02: "Partikel treffen auf den Lösungsmittelstrom und werden gebunden — die Abscheiderate steigt auf fast 95 %.",
        sim_static_stage03: "STUFE 03",
        sim_static_title03: "Desorber",
        sim_static_desc03: "Wärme setzt einen reinen CO₂-Strom nach oben frei — die Reinheit übersteigt 95 %.",
        sim_static_stage04: "STUFE 04",
        sim_static_title04: "Ausgang",
        sim_static_desc04: "Komprimiertes CO₂ tritt aus. Realisiert als 7-phasige Unity-Coroutine mit Blender-Modellen in C#.",
        sim_eyebrow: "Die Simulation",
        sim_intro: "Ein siebenphasiges Unity-Modell der industriellen Post-Combustion-CO₂-Abscheidung für ein 1000-MW-Referenzkraftwerk. Scrolle, um sie laufen zu lassen.",
        sim_cta_build: "WebGL-Build starten",
        sim_cta_case: "Fallstudie lesen",
        systems_eyebrow: "Ausgewählte Systeme",
        stack_eyebrow2: "Der Stack",
        stack_proof_hint: "Jede Zelle nennt, wo ich es tatsächlich eingesetzt habe.",
        traj_eyebrow: "Werdegang",
        hand_eyebrow: "Vernetzen wir uns",
        hand_intro: "Offen für Werkstudentenstellen ab Q2 2026 — hybrid oder remote, Deutschland. Erzähl mir, was du baust.",
        copy_done: "Kopiert",
        footer_tagline: "Backend-Systeme, Echtzeit-Simulation und natives iOS — von Anfang bis Ende umgesetzt.",
        heatmap_title: "GitHub-Aktivität",
        heatmap_hint: "illustrativ · Profil öffnen für Live-Graph →",

        /* ---- v2: Navigation (9 Sektionen) ---- */
        nav_identity: "Identität",
        nav_simulation: "Simulation",
        nav_systems: "Systeme",
        nav_capabilities: "Leistungen",
        nav_stack: "Stack",
        nav_trajectory: "Werdegang",
        nav_now: "Aktuell",

        /* ---- v2: Hero-ProfileCard ---- */
        pc_role: "Backend · iOS · Simulation Entwickler",
        pc_status: "Offen für Stellen",
        pc_contact: "Kontakt",

        /* ---- v2: Über-mich-Sektion ---- */
        ab_stats: [
            { n: 5,    suf: "",  lbl: "Projekte umgesetzt" },
            { n: 7,    suf: "",  lbl: "Unity-Simulationsphasen" },
            { n: 55,   suf: "+", lbl: "Live-Ticker · 5 Börsen" },
            { n: 1000, suf: "+", lbl: "Teilnehmende geleitet · VITOPIA 2024" }
        ],
        ab_sign: "Mit Neugier arbeiten, mit Belegen liefern.",
        idcard_hint: "Karte in beliebige Richtung ziehen und loslassen — sie fällt und schwingt am Band.",

        /* ---- v2: AKTUELL (in Arbeit) ---- */
        now_h2: "Gerade im Bau",
        now_intro: "Live-Prozesse — was gerade läuft.",
        now_p1_name: "HCAI · Adaptives Lernpfad-System",
        now_p1_desc: "LLM-gestützter Tutor mit Chain-of-Thought-Prompting und LLM-as-Judge-Bias-Evaluation. Gemini + lokales Llama 3 via Ollama, LangChain, Guardrails AI. 4-köpfiges OVGU-Team — Paper fällig Juli 2026.",
        now_p1_status: "RUNNING",
        now_p2_name: "Dieses Portfolio",
        now_p2_desc: "Handgebautes Vanilla-JS-Instrumentenpanel — GSAP + Lenis Scroll-Engine, zweisprachig EN/DE, zwei Themes, null Frameworks.",
        now_p2_status: "LIVE",

        /* ---- v2: Befehlspalette (⌘K) ---- */
        cmdk_placeholder: "Zu Sektion springen, Theme wechseln, E-Mail kopieren…",
        cmdk_empty: "Keine Treffer",
        cmdk_group_nav: "Navigation",
        cmdk_group_docs: "Dokumente",
        cmdk_group_links: "Links",
        cmdk_group_act: "Aktionen",
        cmdk_theme: "Theme wechseln",
        cmdk_lang: "Switch to English",
        cmdk_copy: "E-Mail-Adresse kopieren",
        cmdk_cv: "Lebenslauf herunterladen (PDF)",
        cmdk_cv_en: "Lebenslauf herunterladen — Englisch (PDF)",
        cmdk_cv_de: "Lebenslauf herunterladen — Deutsch (PDF)",
        cmdk_case: "CO₂-Simulation — Fallstudie lesen",
        cmdk_unity: "CO₂-Simulation starten (Unity-Build)",
        cmdk_stockwatch: "StockWatch — iOS-App-Repo (GitHub)",
        cmdk_now: "/now öffnen — woran ich arbeite",
        cmdk_uses: "/uses öffnen — mein Toolkit",
        cmdk_github: "GitHub-Profil öffnen",
        cmdk_linkedin: "LinkedIn-Profil öffnen",
        cmdk_results: "Treffer",
        cmdk_result: "Treffer",
        cmdk_hint_nav: "navigieren",
        cmdk_hint_sel: "auswählen",
        cmdk_hint_close: "schließen",

        /* ---- v2: Mobile-Drawer + Teilen ---- */
        drawer_title: "Menü",
        share_btn: "Dieses Portfolio teilen",
        share_ok: "Link kopiert",

        /* ---- v2: lokalisierte Aria-Labels (data-i18n-attr) ---- */
        a11y_chapters: "Kapitel",
        a11y_close_menu: "Menü schließen",
        a11y_open_menu: "Menü öffnen",
        a11y_cmdk_label: "Befehlspalette",
        a11y_cmdk_open: "Befehlsmenü öffnen (Strg+K oder Command+K)",
        a11y_idcard: "Hashwanth Ghanta — Studierendenausweis M.Sc. Digital Engineering, OVGU Magdeburg",
        a11y_heatmap: "GitHub-Aktivität — mein GitHub-Profil mit dem echten Beitragsgraphen öffnen (öffnet in neuem Tab)",
        rail_01: "01 — Identität",
        rail_02: "02 — Über mich",
        rail_03: "03 — Simulation",
        rail_04: "04 — Systeme",
        rail_05: "05 — Leistungen",
        rail_06: "06 — Stack",
        rail_07: "07 — Werdegang",
        rail_08: "08 — Aktuell",
        rail_09: "09 — Kontakt",
        ann_lang: "Sprache: Deutsch",
        ann_theme_dark: "Dunkles Theme aktiv",
        ann_theme_light: "Helles Theme aktiv",
        a11y_sections: "Sektionen",
        a11y_language: "Sprache",
        a11y_secondary: "Sekundär",
        a11y_social: "Social Media",
        a11y_back_top: "Nach oben",
        a11y_commands: "Befehle",
        a11y_profilecard: "Profilkarte",
        a11y_studentid_mount: "Studierendenausweis",
        a11y_copy_email: "E-Mail-Adresse kopieren",
        a11y_copy_linkedin: "LinkedIn-URL kopieren",
        a11y_copy_github: "GitHub-URL kopieren",
        a11y_coursework: "Lehrveranstaltungen",
        a11y_theme_to_light: "Zum hellen Theme wechseln",
        a11y_theme_to_dark: "Zum dunklen Theme wechseln",
        cursor_drag: "ZIEHEN",
        skills_eyebrow: "Belege, keine Selbsteinschätzung",
        skills_h2: "Fähigkeiten",
        track_eyebrow: "Werdegang",
        track_h2: "Umgesetzt & geleitet",
        edu_eyebrow: "Studium",
        education_h2: "Wo ich studiert habe",
        nav_skills: "Fähigkeiten",
        nav_track: "Erfahrung",
        nav_education: "Bildung",
        cf_heading: "Nachricht senden",
        ct_location: "Standort",
        about_h2:  "Über mich",
        about_text:"M.Sc.-Student Digital Engineering an der OVGU Magdeburg mit Schwerpunkt Backend, Simulation und iOS. Ich setze Projekte vollständig um — Unity-3D-Simulationen in C#, native SwiftUI-Apps mit Finanz-Livedaten, IoT-Prototypen auf Arduino. Mir sind sauberer Code, messbare Ergebnisse und die unscheinbaren Details wichtig, die Software tatsächlich funktionieren lassen.",
        stat_phases:"Phasen der Unity-Simulation umgesetzt",
        stat_projects:"Live-Tickerwerte über 5 Börsen",
        stat_available:"Teilnehmende geleitet (VITOPIA 2024)",
        creds_avail_lbl:"Verfügbarkeit",
        creds_avail_val:"Werkstudent ab Q2 2026 · hybrid oder remote, Deutschland · berechtigt für Werkstudentenstellen",
        creds_status_lbl:"Arbeitsstatus",
        creds_status_val:"In Deutschland eingeschriebener Student — berechtigt für Werkstudentenstellen",
        creds_lang_lbl:"Sprachen",
        creds_lang_val:"Englisch (fließend) · Deutsch A2 (an der OVGU eingeschrieben)",
        services_h2:"Was ich mache",
        projects_h2:"Projekte",
        contact_h2:"Lass uns vernetzen",
        contact_lede:"Verfügbar Q2 2026 für Werkstudentenstellen — Backend, Frontend, Data Engineering, Analytics, Datenbanken, iOS, Simulation oder jeder Tech-Bereich. Hybrid oder Remote, Deutschland. Schnellste Antwort: E-Mail.",
        ct_email:"E-Mail", ct_linkedin:"LinkedIn", ct_github:"GitHub",
        cf_name:"Dein Name", cf_email:"Deine E-Mail", cf_msg:"Nachricht",
        btn_send:"Nachricht senden",
        live: "Live-Projekt",
        details: "Details",
        cf_ok: "Nachricht gesendet. Ich melde mich bald.",
        cf_err: "Etwas ist schiefgelaufen — bitte direkt per E-Mail.",
        heroChips: ["C#", "SQL", "Python", "Swift", "SwiftUI", "Xcode", "JavaScript", "GitHub", "Unity 3D", "Blender"],
        skillsGroups: [
            { category: "3D & Simulation",
              proofs: [
                  { name: "Unity 3D", note: "7-phasige CO₂-Abscheidungs-Simulation", href: "#project-01" },
                  { name: "C# (Unity)", note: "Modulare Manager-Architektur über alle Phasen", href: "#project-01" },
                  { name: "TextMeshPro / URP", note: "Custom In-Engine-UI für Parameter-Slider", href: "#project-01" },
              ],
              chips: ["Unity 3D", "C#", "TextMeshPro", "URP", "3D-Modellierung", "Simulationsdesign"] },
            { category: "Backend & Programmierung",
              proofs: [
                  { name: "Python", note: "Datenaufbereitung + Ad-hoc-Pipelines (Analytik-Projekte)", href: "#project-05" },
                  { name: "SQL", note: "OVGU Datenbankkonzepte + Analytik-Coursework", href: "#education" },
                  { name: "Swift / SwiftUI", note: "StockWatch iOS-App, MVVM + async/await", href: "https://github.com/hashwanthghanta/stockwatch-ios" },
                  { name: "JavaScript", note: "Dieses Portfolio — Vanilla JS, kein Framework", href: "https://github.com/hashwanthghanta/hashwanthghanta.github.io" },
              ],
              chips: ["Python", "SQL", "JavaScript", "Swift", "SwiftUI", "C (Arduino)"] },
            { category: "Werkzeuge & Plattformen",
              proofs: [
                  { name: "Git / GitHub", note: "Öffentliche Repos für Portfolio + StockWatch", href: "https://github.com/hashwanthghanta" },
                  { name: "Arduino / Raspberry Pi", note: "IoT-Helm + Ambulanz-Vorrang-Controller", href: "#project-03" },
              ],
              chips: ["Git", "GitHub", "Jira", "SAP", "Arduino", "Raspberry Pi"] },
            { category: "Aktuell im Aufbau (2025–26)",
              proofs: [
                  { name: "LLMs / Hugging Face", note: "Baue eine kleine RAG-Demo über meine eigenen Projekte", href: "#projects" },
                  { name: "Prompt Engineering", note: "Täglich im Einsatz für Pair-Programming, Code-Reviews und Refactorings", href: "#projects" },
              ],
              chips: ["LLMs", "Hugging Face", "Prompt Engineering", "Transformers", "KI/ML-Konzepte"] },
            { category: "Bearbeitung & Visualisierung",
              proofs: [
                  { name: "Premiere Pro", note: "Schnitt des CO₂-Simulation-Walkthroughs", href: "#project-01" },
                  { name: "Blender", note: "Sechs ingenieurgenaue 3D-Anlagenkomponenten modelliert", href: "#project-01" },
              ],
              chips: ["Adobe", "Videography", "Animation", "Farbkorrektur", "3D-Modellierung"] },
            { category: "Daten & Analytik",
              proofs: [
                  { name: "Power BI", note: "Tata Datenvisualisierungs-Zertifizierungs-Dashboards", href: "#project-05" },
                  { name: "Excel", note: "Microsoft Business Analysis + Finanzmodellierung", href: "#project-05" },
              ],
              chips: ["Power BI", "Excel", "Datenvisualisierung", "Business Analytics"] },
        ],
        track: [
            { date: "2025 – Heute", role: "Simulations- & Laborprojekte", org: "OVGU Magdeburg · Digital Engineering",
              body: "Entwicklung von Unity-Simulationen, C#-Architektur und interaktiven UI-Workflows in Labor- und Modulprojekten." },
            { date: "2025 – Heute", role: "Webentwicklung — Portfolio & Case Studies", org: "Eigenes Projekt",
              body: "Konzeption und Umsetzung eines zweisprachigen Portfolios mit Fokus auf Nutzer-UX, Accessibility und Performance." },
            { date: "2024", role: "Ehrenamtlicher Leiter — VITOPIA 2024", org: "Jährliches Kulturfestival der VIT-AP Universität, Indien",
              body: "Organisation des größten jährlichen Uni-Events mit über 1.000 Teilnehmern, darunter Studierende und Gastauftritte. Verantwortlich für Logistik, Studierendenteams, Veranstaltungsplanung und Live-Aktivitäten." },
        ],
        education: [
            { iconKey: "grad", degree: "M.Sc. Digital Engineering", period: "April 2025 – Heute",
              detail: "<strong>OVGU, Magdeburg, Deutschland</strong>",
              focusAreasLabel: "Schwerpunkte",
              focusAreas: ["Digitale Systeme", "Simulation", "Software-Engineering", "Data Science"],
              subjectsLabel: "Lehrveranstaltungen",
              subjects: [
                  { name: "DE-Visualisierungsprojekt", focus: true },
                  { name: "Datenbankkonzepte" },
                  { name: "Data Mining" },
                  { name: "KI-gestützte Entscheidungsunterstützung" },
                  { name: "Einführung in die Informatik" },
              ] },
            { iconKey: "zap", degree: "B.Tech Elektrotechnik & Kommunikation", period: "2020 – 2024",
              detail: "<strong>VIT-AP Universität, Indien</strong><br>CGPA 7,72 / 10,0",
              focusAreasLabel: "Schwerpunkte",
              focusAreas: ["IoT", "Eingebettete Systeme", "Drahtlose Kommunikation"] },
            { iconKey: "award", degree: "Zertifizierungen", period: "2023 – 2024",
              badges: ["Datenvisualisierung – Tata","Business Analysis – Microsoft","Business Analytics – Coursera","IoT Cloud Computing – Coursera","IoT Boards Programmierung – Coursera","Projektmanagement – Coursera","Power BI Workshop"] },
        ],
        services: [
            { name: "Software- & Backend-Entwicklung",       desc: "Saubere objektorientierte Programmierung (OOP) in C# und Swift, robuste Backend-Architektur, Datenbankintegration (SQL) und optimierte Logikimplementierung." },
            { name: "iOS- & SwiftUI-Entwicklung",    desc: "Native iOS-Apps in SwiftUI mit MVVM, async/await-Networking, interaktiven Swift Charts und vollständiger Englisch- + Deutsch-Lokalisierung." },
            { name: "Datenvisualisierung & Analytik",desc: "Power-BI-Dashboards, Excel-Modelle und Python-Pipelines, die Betriebsdaten in klare KPIs, trends und Entscheidungsgrundlagen verwandeln." },
            { name: "IoT & Embedded Systems",        desc: "Arduino- und Mikrocontroller-Systeme für sicherheitskritische Anwendungen — Smart-Helme, Ambulanz-Vorrang, Ultraschall-Blindzonen-Erkennung." },
            { name: "Web- & Markendesign",           desc: "Zweisprachige Portfolios und Case-Study-Seiten mit zugänglichem Markup, performance-first UI und klarer visueller Identität." },
        ],
        projects: [
            {
                num: "01",
                cat: "Hervorgehoben · Unity 3D + Blender",
                name: "Post-Combustion CO₂-Abscheidungs-Simulation",
                period: "2025 – 2026",
                desc: "Fünfköpfiges OVGU-Magdeburg-Teamprojekt zur Simulation der industriellen Post-Combustion-CO₂-Abscheidung für ein 1000-MW-Referenzkraftwerk. Meine Rolle: Unity- & Blender-Entwickler. Sechs ingenieurgenaue 3D-Modelle in Blender 4.x, eine siebenphasige Unity-Coroutine in C#, zwei Live-Temperatur-Slider steuern die Partikelsysteme und den Effizienz-Graphen.",
                highlights: [
                    "5-Personen-Zusammenarbeit zwischen Digital- und Verfahrenstechnik an der OVGU Magdeburg",
                    "Zwei Live-Temperatur-Slider — Absorber 0–65°C und Stripper 75–125°C — steuern Partikelfarbe, -dichte und Effizienz-Graph in Echtzeit",
                    "Sechs ingenieurgenaue 3D-Modelle (Absorber, Stripper, Reboiler, Wärmetauscher, Kompressor, CO₂-Tank) in Blender 4.x modelliert, via FBX nach Unity exportiert",
                    "11 C#-Skripte nach Singleton- + partiellem ECS-Muster; Überhitzungs-Watchdog stoppt bei 125°C automatisch",
                    "Live spielbar auf Unity Play — ohne Installation",
                ],
                learned: "Apply Transform beim FBX-Export ist Pflicht — ohne diese Option landet Blenders Z-up-Welt in Unitys Y-up-Szene um 90° rotiert und im Maßstab 1/100. Eine Checkbox hat uns eine Woche Pipeline-Debugging erspart.",
                tags: ["Unity 2022 LTS", "C#", "Blender 4.x", "TextMeshPro", "UI Toolkit", "FBX-Pipeline", "Simulation"],
                url:  "https://play.unity.com/en/games/30f22392-532c-41e1-b925-6191a9ea99c2/post-combustion-co-carbon-capture",
                urlLabel: "Live-Demo öffnen",
                caseStudy: "projects/co2-simulation-de.html",
                caseStudyLabel: "Case Study lesen",
                img1: "Images/co2-simulation.webp",
                img2: "Images/co2-preview.jpg",
            },
            {
                num: "02",
                cat: "Open Source · iOS · SwiftUI",
                name: "StockWatch — SwiftUI-Watchlist für iOS",
                period: "2026",
                desc: "Native iOS-Watchlist-App, inspiriert von Scalable Capital. Live-Kurse von Yahoo Finance, 55+ Ticker aus US-, deutschen (Xetra), britischen, Schweizer und dänischen Börsen, Listen- + Grid-Layout, interaktive Swift-Charts-Detailansicht mit sieben Zeiträumen, symbolbezogene News, EN/DE-Sprachumschalter zur Laufzeit, Hell/Dunkel/System-Theming.",
                highlights: [
                    "Interaktive Swift-Charts-Detailansicht zum Scrubbing von Schlusskurs und Datum",
                    "MVVM mit @MainActor @Observable, Protokoll-basierte DI, async/await + URLSession",
                    "Sprachumschalter Englisch / Deutsch zur Laufzeit über Bundle-Swizzling",
                    "XCTest-Suite deckt Persistenz, Refresh-Übergänge und Prozent-Mathematik ab",
                ],
                learned: "Protokoll-basierte DI + @MainActor @Observable machten die XCTest-Suite trivial — ich konnte einen Fake-Yahoo-Client in das ViewModel einsetzen, ohne den Produktionscode zu berühren.",
                tags: ["Swift", "SwiftUI", "Swift Charts", "async/await", "MVVM", "XCTest", "iOS 17+"],
                url:  "https://github.com/hashwanthghanta/stockwatch-ios",
                urlLabel: "Auf GitHub ansehen",
                caseStudy: "projects/stockwatch-de.html",
                caseStudyLabel: "Case Study lesen",
                img1: "Images/stockwatch-thumb-sm.jpg",
                img2: "Images/v6_grid_dark-sm.jpg",
            },
            {
                num: "03",
                cat: "IoT · Arduino",
                name: "IoT Smart-Helm & Fahrradsicherheitssystem",
                period: "2024",
                desc: "GPS- und Alkoholsensor-ausgestatteter Smart-Helm zur Erkennung unsicherer Fahrbedingungen und automatischen Alarmierung von Notfallkontakten. Konzipiert zur Reduzierung von Motorradunfällen durch Echtzeit-Überwachung.",
                highlights: [
                    "GPS-Modul + Alkoholsensor auf Arduino-Mikrocontroller",
                    "Automatische Notfall-Alarmierung bei unsicherer Bedingung",
                    "Feldgetestete Wearable-Bauform",
                ],
                learned: "Reine Software-Sperren sind Theater — die Zündung bleibt nur blockiert, weil das Relais physisch in Reihe mit dem Anlasser hängt. Den MQ-3 im Firmware-Setup kalibrieren, nicht erst am Werktisch, sonst scheitert die erste Demo.",
                tags: ["NodeMCU", "ATmega328P", "FSR", "MQ-3", "GSM", "GPS", "Embedded C"],
                svg: "iot_helmet",
                caseStudy: "projects/iot-helmet-de.html",
                caseStudyLabel: "Case Study lesen",
            },
            {
                num: "04",
                cat: "IoT · Embedded · B.Tech",
                name: "IoT-Sicherheitssysteme — Verkehr & Fahrzeug",
                period: "2022 – 2023",
                desc: "Zwei eingebettete Systemprojekte aus dem B.Tech-Studium: ein Kreuzungs-Controller, der Rettungswagen Vorrang gibt, und ein Ultraschall-Toter-Winkel-Detektor für Fahrzeuge. Beides auf Arduino- und Mikrocontroller-Plattformen in Embedded C umgesetzt.",
                highlights: [
                    "Kreuzungs-Controller mit Ambulanz-Vorrang — RF + Mikrocontroller",
                    "Ultraschall-Toter-Winkel-Detektor mit akustischer/visueller Fahrerwarnung",
                    "Embedded C auf Arduino-Hardware",
                ],
                learned: "Zwei Sicherheitssysteme, eine Lektion: Ein Alarm, den niemand hört, ist kein Alarm. Den Ton des Toter-Winkel-Detektors musste ich am Motorgeräusch ausrichten — danach designe ich Feedback fürs reale Umfeld, nicht für die Werkbank.",
                tags: ["IoT", "Arduino", "Sensoren", "Embedded C"],
                svg: "iot_safety",
            },
            {
                num: "05",
                cat: "Data · Analytik · BI",
                name: "Datenanalyse & Business-Intelligence-Dashboards",
                period: "2023 – 2024",
                desc: "Power-BI-Dashboards und Excel-Modelle für Geschäftsdatenanalysen im Rahmen von Zertifizierungsprogrammen mit Tata und Microsoft. Datenvisualisierung zur klaren Darstellung von KPIs, Trends und Betriebskennzahlen für nicht-technische Stakeholder.",
                highlights: [
                    "Power-BI-Dashboards übersetzen Betriebsdaten in KPI-Sichten",
                    "Excel-Finanz-/Forecasting-Modelle mit Named-Range-Refactoring",
                    "Python-Pipelines für Datenaufbereitung und Ad-hoc-Analyse",
                ],
                learned: "Nicht-technische Stakeholder lesen Dashboards wie Entwickler einen Stacktrace — von oben nach unten, auf der Suche nach der einen Zahl, die falsch ist. Ich designe Dashboards seitdem mit der Kernkennzahl zuerst, Drill-down danach.",
                tags: ["Power BI", "Excel", "Datenvisualisierung", "Business Analytics", "Python"],
                svg: "analytics",
            },
        ],
    },
};
