/* SVG mockups for projects without real screenshots (IoT helmet, IoT safety, data). */
const PROJ_SVG = {
    iot_helmet: `<svg viewBox="0 0 380 240" xmlns="http://www.w3.org/2000/svg"><rect width="380" height="240" fill="#0a1628"/><defs><radialGradient id="ihg" cx="0.5" cy="0.4" r="0.6"><stop offset="0%" stop-color="rgba(34,211,238,0.35)"/><stop offset="100%" stop-color="rgba(34,211,238,0)"/></radialGradient></defs><rect width="380" height="240" fill="url(#ihg)"/><line x1="50" y1="120" x2="130" y2="120" stroke="rgba(34,211,238,0.4)" stroke-width="1.5"/><line x1="130" y1="120" x2="130" y2="65" stroke="rgba(34,211,238,0.4)" stroke-width="1.5"/><line x1="130" y1="65" x2="200" y2="65" stroke="rgba(34,211,238,0.7)" stroke-width="1.5"/><line x1="200" y1="65" x2="270" y2="120" stroke="rgba(34,211,238,0.4)" stroke-width="1.5"/><line x1="270" y1="120" x2="340" y2="120" stroke="rgba(34,211,238,0.4)" stroke-width="1.5"/><line x1="200" y1="65" x2="200" y2="170" stroke="rgba(34,211,238,0.3)" stroke-width="1.5"/><line x1="130" y1="120" x2="130" y2="170" stroke="rgba(34,211,238,0.3)" stroke-width="1.5"/><line x1="270" y1="120" x2="270" y2="170" stroke="rgba(34,211,238,0.3)" stroke-width="1.5"/><circle cx="50"  cy="120" r="6" fill="rgba(34,211,238,0.9)"/><circle cx="130" cy="120" r="10" fill="rgba(34,211,238,0.15)" stroke="rgba(34,211,238,0.85)" stroke-width="1.5"/><circle cx="200" cy="65"  r="14" fill="rgba(34,211,238,0.18)" stroke="rgba(34,211,238,1)" stroke-width="2"/><circle cx="270" cy="120" r="10" fill="rgba(34,211,238,0.15)" stroke="rgba(34,211,238,0.85)" stroke-width="1.5"/><circle cx="340" cy="120" r="6" fill="rgba(34,211,238,0.75)"/><circle cx="130" cy="170" r="5" fill="rgba(34,211,238,0.55)"/><circle cx="200" cy="170" r="5" fill="rgba(34,211,238,0.55)"/><circle cx="270" cy="170" r="5" fill="rgba(34,211,238,0.55)"/><text x="186" y="60" fill="rgba(34,211,238,0.95)" font-size="9" font-family="monospace" font-weight="600">GPS</text><path d="M324 102 Q333 90 342 102" stroke="rgba(34,211,238,0.65)" fill="none" stroke-width="1.6" stroke-linecap="round"/><path d="M318 93  Q333 76 348 93"  stroke="rgba(34,211,238,0.4)"  fill="none" stroke-width="1.6" stroke-linecap="round"/><rect x="18" y="14" width="120" height="24" rx="4" fill="rgba(34,211,238,0.10)" stroke="rgba(34,211,238,0.25)"/><text x="28" y="30" fill="rgba(34,211,238,0.7)" font-size="10" font-family="monospace">ALCOHOL + GPS</text></svg>`,
    iot_safety: `<svg viewBox="0 0 380 240" xmlns="http://www.w3.org/2000/svg"><rect width="380" height="240" fill="#0d1117"/><rect x="173" y="18" width="14" height="200" fill="rgba(255,255,255,0.05)" rx="3"/><rect x="152" y="32" width="56" height="120" rx="9" fill="rgba(17,24,39,0.95)" stroke="rgba(255,255,255,0.12)" stroke-width="1"/><circle cx="180" cy="60" r="16" fill="rgba(239,68,68,0.92)"/><circle cx="180" cy="60" r="22" fill="rgba(239,68,68,0.18)"/><circle cx="180" cy="98" r="16" fill="rgba(255,255,255,0.06)"/><circle cx="180" cy="138" r="16" fill="rgba(34,197,94,0.12)"/><rect x="50" y="156" width="64" height="38" rx="4" fill="rgba(248,250,252,0.9)"/><rect x="50" y="156" width="16" height="38" rx="4" fill="rgba(239,68,68,0.85)"/><circle cx="66" cy="198" r="8" fill="rgba(30,30,30,0.9)"/><circle cx="96" cy="198" r="8" fill="rgba(30,30,30,0.9)"/><text x="76" y="180" fill="rgba(239,68,68,0.95)" font-size="12" font-family="monospace" font-weight="bold">+</text><rect x="252" y="106" width="86" height="46" rx="5" fill="rgba(17,24,39,0.75)" stroke="rgba(99,102,241,0.45)" stroke-width="1"/><text x="262" y="128" fill="rgba(129,140,248,0.85)" font-size="9" font-family="monospace">ULTRASONIC</text><text x="262" y="142" fill="rgba(129,140,248,0.65)" font-size="8" font-family="monospace">BLIND SPOT</text><line x1="208" y1="128" x2="252" y2="128" stroke="rgba(99,102,241,0.4)" stroke-dasharray="5 3"/><rect x="18" y="14" width="135" height="24" rx="4" fill="rgba(99,102,241,0.08)" stroke="rgba(99,102,241,0.2)"/><text x="28" y="30" fill="rgba(129,140,248,0.7)" font-size="10" font-family="monospace">SAFETY SYSTEMS</text></svg>`,
    analytics:  `<svg viewBox="0 0 380 240" xmlns="http://www.w3.org/2000/svg"><rect width="380" height="240" fill="#0d1b2a"/><line x1="0" y1="190" x2="380" y2="190" stroke="rgba(255,255,255,0.07)" stroke-dasharray="4 4"/><line x1="0" y1="140" x2="380" y2="140" stroke="rgba(255,255,255,0.07)" stroke-dasharray="4 4"/><line x1="0" y1="90"  x2="380" y2="90"  stroke="rgba(255,255,255,0.07)" stroke-dasharray="4 4"/><rect x="32"  y="120" width="38" height="68"  fill="rgba(8,145,178,0.55)"  rx="3"/><rect x="92"  y="78"  width="38" height="110" fill="rgba(8,145,178,0.75)"  rx="3"/><rect x="152" y="98"  width="38" height="90"  fill="rgba(8,145,178,0.62)"  rx="3"/><rect x="212" y="58"  width="38" height="130" fill="rgba(14,165,233,0.85)" rx="3"/><rect x="272" y="82"  width="38" height="106" fill="rgba(8,145,178,0.68)"  rx="3"/><rect x="332" y="68"  width="38" height="120" fill="rgba(8,145,178,0.78)"  rx="3"/><polyline points="50,128 110,82 170,102 230,68 290,90 350,72" stroke="#22d3ee" stroke-width="2.4" fill="none" stroke-linecap="round" stroke-linejoin="round"/><circle cx="50"  cy="128" r="4" fill="#22d3ee"/><circle cx="110" cy="82"  r="4" fill="#22d3ee"/><circle cx="170" cy="102" r="4" fill="#22d3ee"/><circle cx="230" cy="68"  r="4" fill="#22d3ee"/><circle cx="290" cy="90"  r="4" fill="#22d3ee"/><circle cx="350" cy="72"  r="4" fill="#22d3ee"/><rect x="18" y="14" width="120" height="26" rx="5" fill="rgba(255,255,255,0.05)"/><text x="30" y="32" fill="rgba(255,255,255,0.55)" font-size="11" font-family="monospace">POWER BI</text></svg>`,
};

const DATA = {
    en: {
        nav_about: "About",
        nav_services: "What I Do",
        nav_projects: "Projects",
        nav_contact: "Contact",
        marquee_h2: "Selected Work",
        hero_open: "Available Q2 2026 — Working Student (Hybrid or Remote, Germany)",
        hero_tag:  "I built a 7-phase Unity simulation of industrial CO₂ capture, a 55-ticker SwiftUI iOS watchlist with live Yahoo Finance, and an IoT helmet that auto-calls emergency contacts.",
        hero_intro:"M.Sc. Digital Engineering at OVGU Magdeburg — a programme spanning backend systems, databases, data science, simulation, AI, and software engineering. I shipped a 7-phase Unity 3D CO₂ capture simulation and I'm building an AI adaptive learning system with LLMs. Open to working-student roles across backend, frontend, data engineering, analytics, databases, iOS, simulation — or any tech domain. I pick up new technologies fast. Hybrid or remote, starting Q2 2026.",
        btn_resume: "Resume",
        btn_projects: "View Projects",
        btn_contact_me: "Contact Me",
        btn_get_in_touch: "Get In Touch",
        skills_eyebrow: "Proof, not self-ratings",
        skills_h2: "Skills",
        track_eyebrow: "Track Record",
        track_h2: "Shipped & Led",
        edu_eyebrow: "Studied",
        education_h2: "Where I Studied",
        nav_skills: "Skills",
        nav_track: "Experience",
        nav_education: "Education",
        cf_heading: "Send a message",
        ct_location: "Location",
        about_h2:  "About Me",
        about_text:"I'm an M.Sc. Digital Engineering student at OVGU Magdeburg focused on backend, simulation, and iOS. I ship things end-to-end — Unity 3D simulations in C#, native SwiftUI apps with live finance data, IoT prototypes on Arduino. I care about clean code, measurable outcomes, and the boring details that make software actually work.",
        stat_phases:"Unity simulation phases shipped",
        stat_projects:"Live stock tickers across 6 exchanges",
        stat_available:"Participants led at VITOPIA 2024",
        creds_avail_lbl:"Availability",
        creds_avail_val:"Working Student · Q2 2026 · hybrid or remote",
        creds_status_lbl:"Work status",
        creds_status_val:"Enrolled student in Germany — eligible for Werkstudent roles",
        creds_lang_lbl:"Languages",
        creds_lang_val:"English (fluent) · German A2 (enrolled at OVGU)",
        services_h2:"What I Do",
        projects_h2:"Projects",
        contact_h2:"Let's Connect",
        contact_lede:"Available Q2 2026 for working-student roles — backend, frontend, data engineering, analytics, databases, iOS, simulation, or any tech domain. Hybrid or remote, Germany. Fastest reply: email.",
        ct_email:"Email", ct_linkedin:"LinkedIn", ct_github:"GitHub",
        cf_name:"Your name", cf_email:"Your email", cf_msg:"Message",
        btn_send:"Send Message",
        live: "Live Project",
        details: "Details",
        cf_ok: "Message sent. I will get back to you soon.",
        cf_err: "Something went wrong — please email me directly.",
        heroChips: ["C#", "SQL", "Python", "Swift", "SwiftUI", "Xcode", "JavaScript", "GitHub", "Unity 3D", "Blender"],
        skillsGroups: [
            { category: "3D & Simulation",
              proofs: [
                  { name: "Unity 3D", note: "7-phase CO₂ capture simulation", href: "#project-01" },
                  { name: "C# (Unity)", note: "Modular manager architecture across simulation phases", href: "#project-01" },
                  { name: "TextMeshPro / URP", note: "Custom in-engine UI for parameter sliders", href: "#project-01" },
              ],
              chips: ["Unity 3D", "C#", "TextMeshPro", "URP", "3D Modeling", "Simulation Design"] },
            { category: "Backend & Programming",
              proofs: [
                  { name: "Python", note: "Data prep + ad-hoc pipelines (analytics projects)", href: "#project-05" },
                  { name: "SQL", note: "OVGU Database Concepts coursework + analytics", href: "#education" },
                  { name: "Swift / SwiftUI", note: "StockWatch iOS app, MVVM + async/await", href: "https://github.com/hashwanthghanta/stockwatch-ios" },
                  { name: "JavaScript", note: "This portfolio — vanilla JS, no framework", href: "https://github.com/hashwanthghanta/hashwanthghanta.github.io" },
              ],
              chips: ["Python", "SQL", "JavaScript", "Swift", "SwiftUI", "SwiftUX", "C (Arduino)"] },
            { category: "Tools & Platforms",
              proofs: [
                  { name: "Git / GitHub", note: "Public repos for portfolio + StockWatch", href: "https://github.com/hashwanthghanta" },
                  { name: "Arduino / Raspberry Pi", note: "IoT helmet + ambulance-priority controller", href: "#project-03" },
              ],
              chips: ["Git", "GitHub", "Jira", "SAP", "Arduino", "Raspberry Pi"] },
            { category: "Currently learning (2025–26)",
              proofs: [
                  { name: "LLMs / Hugging Face", note: "Building a small RAG demo over my own projects", href: "#projects" },
                  { name: "Prompt engineering", note: "Used daily for pair-programming, code review, and refactors", href: "#projects" },
              ],
              chips: ["LLMs", "Hugging Face", "Prompt Engineering", "Transformers", "AI/ML Concepts"] },
            { category: "Editing & Visualization",
              proofs: [
                  { name: "Premiere Pro", note: "Edited the CO₂ simulation walkthrough", href: "#project-01" },
                  { name: "Blender", note: "Modelling six engineering-accurate 3D plant components", href: "#project-01" },
              ],
              chips: ["Adobe", "Videography", "Animation", "Colour Grading", "3D Modeling"] },
            { category: "Data & Analytics",
              proofs: [
                  { name: "Power BI", note: "Tata Data Visualization certification dashboards", href: "#project-05" },
                  { name: "Excel", note: "Microsoft Business Analysis + financial modelling", href: "#project-05" },
              ],
              chips: ["Power BI", "Excel", "Data Visualization", "Business Analytics"] },
        ],
        track: [
            { date: "2025 – Present", role: "Simulation Coursework & Lab Projects", org: "OVGU Magdeburg · Digital Engineering",
              body: "Built Unity simulations, C# system architecture, and interactive UI workflows across lab modules in industrial systems and visualization." },
            { date: "2025 – Present", role: "Web Development — Portfolio & Case Studies", org: "Personal Project",
              body: "Designed and shipped a bilingual portfolio with project case studies, accessibility improvements, and performance-first UI." },
            { date: "2024", role: "Volunteer Head — VITOPIA 2024", org: "VIT-AP University Annual Cultural Festival, India",
              body: "Managed the largest annual college event with 1,000+ participants including students and celebrity guests. Coordinated logistics, student teams, event scheduling, and live activity management across cultural and technical events." },
        ],
        education: [
            { iconKey: "grad", degree: "M.Sc. Digital Engineering", period: "April 2025 – Present",
              detail: "<strong>OVGU, Magdeburg, Germany</strong>",
              focusAreasLabel: "Focus areas",
              focusAreas: ["Digital systems", "Simulation", "Software engineering", "Data science"],
              subjectsLabel: "Coursework",
              subjects: [
                  { name: "DE visualization project", focus: true },
                  { name: "Database concepts" },
                  { name: "Data mining" },
                  { name: "AI best decision support" },
                  { name: "Introduction to computer science engineering" },
              ] },
            { iconKey: "zap", degree: "B.Tech Electronics & Communication", period: "2020 – 2024",
              detail: "<strong>VIT-AP University, India</strong><br>CGPA 7.72 / 10.0",
              focusAreasLabel: "Focus areas",
              focusAreas: ["IoT", "Embedded systems", "Wireless communication"] },
            { iconKey: "award", degree: "Certifications", period: "",
              badges: ["Data Visualization – Tata","Business Analysis – Microsoft","Business Analytics – Coursera","IoT Cloud Computing – Coursera","IoT Programming with Boards – Coursera","Project Management – Coursera","Power BI Workshop"] },
        ],
        services: [
            { name: "Software & Backend Development",       desc: "Clean object-oriented programming (OOP) in C# and Swift, robust backend architecture, database integration (SQL), and optimized logic implementation." },
            { name: "iOS & SwiftUI Development",    desc: "Native iOS apps in SwiftUI with MVVM, async/await networking, interactive Swift Charts, and full English + German localization." },
            { name: "Data Visualization & Analytics", desc: "Power BI dashboards, Excel models, and Python pipelines that turn raw operational data into clear KPIs, trends, and decision support." },
            { name: "IoT & Embedded Systems",       desc: "Arduino and microcontroller systems for safety-critical use cases — smart helmets, ambulance signalling, ultrasonic blind-spot detection." },
            { name: "Web & Brand Design",           desc: "Bilingual portfolios and case-study sites with accessible markup, performance-first UI, and clear visual identity." },
        ],
        projects: [
            {
                num: "01",
                cat: "Featured · Unity 3D + Blender",
                name: "Post-Combustion CO₂ Carbon Capture Simulation",
                period: "2025 – 2026",
                desc: "Five-person OVGU Magdeburg team project simulating industrial post-combustion CO₂ capture for a 1000 MW reference plant. My role: Unity & Blender Developer. Six engineering-accurate 3D models in Blender 4.x, a seven-phase Unity coroutine in C#, two live temperature sliders driving particle systems and the efficiency graph.",
                highlights: [
                    "5-person collaboration across Digital + Chemical Engineering at OVGU Magdeburg",
                    "Two live temperature sliders — absorber 0–65°C and stripper 75–125°C — drive particle colour, density, and the efficiency graph in real time",
                    "Six engineering-accurate 3D models (absorber, stripper, reboiler, heat exchanger, compressor, CO₂ storage tank) modelled in Blender 4.x, exported to Unity via FBX",
                    "11 C# scripts on a Singleton + partial-ECS pattern; overheat watchdog stops everything at 125°C",
                    "Playable live on Unity Play — no install",
                ],
                learned: "Apply Transform on FBX export is non-negotiable — Blender's Z-up world arrives in Unity's Y-up scene rotated 90° and scaled 1/100 without it. One checkbox saved a week of debugging the asset pipeline.",
                tags: ["Unity 2022 LTS", "C#", "Blender 4.x", "TextMeshPro", "UI Toolkit", "FBX pipeline", "Simulation"],
                url:  "https://play.unity.com/en/games/30f22392-532c-41e1-b925-6191a9ea99c2/post-combustion-co-carbon-capture",
                urlLabel: "Open Live Demo",
                caseStudy: "projects/co2-simulation.html",
                caseStudyLabel: "Read case study",
                img1: "Images/co2-simulation.gif",
                img2: "Images/co2-preview.jpg",
            },
            {
                num: "02",
                cat: "Open Source · iOS · SwiftUI",
                name: "StockWatch — SwiftUI Watchlist for iOS",
                period: "2026",
                desc: "Native iOS watchlist app inspired by Scalable Capital. Live Yahoo Finance quotes, 55+ tickers across US, German Xetra, UK, Swiss and Danish exchanges, list + grid layouts, interactive Swift Charts with seven time ranges, symbol-relevant news, EN/DE runtime language switch, Dark/Light/System theming.",
                highlights: [
                    "Interactive Swift Charts detail view — scrub the line to inspect closing price and date",
                    "MVVM with @MainActor @Observable, protocol-based DI, async/await + URLSession",
                    "Runtime English / German language switch via Bundle swizzling",
                    "XCTest suite covering persistence, refresh transitions, and percent-change math",
                ],
                learned: "Protocol-based DI + @MainActor @Observable made the XCTest suite trivial — I swapped a fake Yahoo client into the ViewModel without touching production code paths.",
                tags: ["Swift", "SwiftUI", "Swift Charts", "async/await", "MVVM", "XCTest", "iOS 17+"],
                url:  "https://github.com/hashwanthghanta/stockwatch-ios",
                urlLabel: "View on GitHub",
                caseStudy: "projects/stockwatch.html",
                caseStudyLabel: "Read case study",
                img1: "Images/stockwatch-thumb-sm.jpg",
                img2: "Images/v6_grid_dark-sm.jpg",
            },
            {
                num: "03",
                cat: "IoT · Arduino",
                name: "IoT Smart Helmet & Bike Safety System",
                period: "2024",
                desc: "GPS and alcohol-sensor-equipped smart helmet that detects unsafe riding conditions and auto-alerts emergency contacts. Built to reduce motorcycle fatalities through real-time monitoring and automated safety enforcement.",
                highlights: [
                    "GPS module + alcohol sensor on Arduino-class microcontroller",
                    "Automated emergency-contact alerting on unsafe-condition detection",
                    "Field-tested wearable form factor",
                ],
                learned: "Software-only gates are theatre — the ignition only stays locked because the relay is physically in series with the starter. Calibrate the MQ-3 in firmware setup, not at the bench, or the first demo fails.",
                tags: ["NodeMCU", "ATmega328P", "FSR", "MQ-3", "GSM", "GPS", "Embedded C"],
                svg: "iot_helmet",
                caseStudy: "projects/iot-helmet.html",
                caseStudyLabel: "Read case study",
            },
            {
                num: "04",
                cat: "IoT · Embedded · B.Tech",
                name: "IoT Safety Systems — Traffic & Vehicle",
                period: "2022 – 2023",
                desc: "Two embedded-systems projects from B.Tech coursework: a traffic-junction controller that gives ambulances signal priority, and an ultrasonic blind-spot detector for vehicles. Both built on Arduino and microcontroller platforms with embedded C.",
                highlights: [
                    "Ambulance-priority traffic junction controller — RF + microcontroller",
                    "Ultrasonic blind-spot detector with audible/visual driver alerts",
                    "Embedded C on Arduino-class hardware",
                ],
                learned: "Two safety devices, one lesson: an alert nobody hears is no alert. The ultrasonic blind-spot tone had to be tuned around engine noise — taught me to design feedback for the real environment, not the bench.",
                tags: ["IoT", "Arduino", "Sensors", "Embedded C"],
                svg: "iot_safety",
            },
            {
                num: "05",
                cat: "Data · Analytics · BI",
                name: "Data Analytics & Business Intelligence Dashboards",
                period: "2023 – 2024",
                desc: "Power BI dashboards and Excel models built for business data analysis as part of certification work with Tata and Microsoft. Applied data visualization principles to surface KPIs, trends, and operational insights for non-technical stakeholders.",
                highlights: [
                    "Power BI dashboards translating operational data into KPI views",
                    "Excel financial / forecasting models with named-range refactoring",
                    "Python pipelines for data prep and ad-hoc analysis",
                ],
                learned: "Non-technical stakeholders read a dashboard the way a developer reads a stack trace — top-down, hunting for the one number that's wrong. I now design dashboards with the headline number first, drill-down second.",
                tags: ["Power BI", "Excel", "Data Visualization", "Business Analytics", "Python"],
                svg: "analytics",
            },
        ],
    },
    de: {
        nav_about: "Über mich",
        nav_services: "Was ich mache",
        nav_projects: "Projekte",
        nav_contact: "Kontakt",
        marquee_h2: "Ausgewählte Arbeiten",
        hero_open: "Verfügbar Q2 2026 — Werkstudent (Hybrid oder Remote, Deutschland)",
        hero_tag:  "Ich habe eine 7-phasige Unity-Simulation der industriellen CO₂-Abscheidung, eine SwiftUI-iOS-Watchlist für 55+ Tickerwerte mit Yahoo-Finance-Livedaten und einen IoT-Helm gebaut, der bei Gefahr automatisch Notfallkontakte anruft.",
        hero_intro:"M.Sc. Digital Engineering an der OVGU Magdeburg — ein Studiengang mit Schwerpunkten in Backend-Systemen, Datenbanken, Data Science, Simulation, KI und Software Engineering. Ich habe eine 7-phasige Unity-3D-CO₂-Simulation umgesetzt und baue ein adaptives KI-Lernsystem mit LLMs. Offen für Werkstudentenstellen in Backend, Frontend, Daten, Analytics, Datenbanken, iOS, Simulation — oder jedem anderen Tech-Bereich. Ich lerne schnell. Hybrid oder Remote, ab Q2 2026.",
        btn_resume: "Lebenslauf",
        btn_projects: "Projekte ansehen",
        btn_contact_me: "Kontakt",
        btn_get_in_touch: "Kontakt aufnehmen",
        skills_eyebrow: "Belege, keine Selbsteinschätzung",
        skills_h2: "Fähigkeiten",
        track_eyebrow: "Werdegang",
        track_h2: "Umgesetzt & geleitet",
        edu_eyebrow: "Studium",
        education_h2: "Wo ich studiert habe",
        nav_skills: "Fähigkeiten",
        nav_track: "Erfahrung",
        nav_education: "Bildung",
        cf_heading: "Nachricht senden",
        ct_location: "Standort",
        about_h2:  "Über mich",
        about_text:"M.Sc.-Student Digital Engineering an der OVGU Magdeburg mit Schwerpunkt Backend, Simulation und iOS. Ich setze Projekte vollständig um — Unity-3D-Simulationen in C#, native SwiftUI-Apps mit Finanz-Livedaten, IoT-Prototypen auf Arduino. Mir sind sauberer Code, messbare Ergebnisse und die unscheinbaren Details wichtig, die Software tatsächlich funktionieren lassen.",
        stat_phases:"Phasen der Unity-Simulation umgesetzt",
        stat_projects:"Live-Tickerwerte über 6 Börsen",
        stat_available:"Teilnehmende geleitet (VITOPIA 2024)",
        creds_avail_lbl:"Verfügbarkeit",
        creds_avail_val:"Werkstudent · ab Q2 2026 · hybrid oder remote",
        creds_status_lbl:"Arbeitsstatus",
        creds_status_val:"In Deutschland eingeschriebener Student — berechtigt für Werkstudentenstellen",
        creds_lang_lbl:"Sprachen",
        creds_lang_val:"Englisch (fließend) · Deutsch A2 (an der OVGU eingeschrieben)",
        services_h2:"Was ich mache",
        projects_h2:"Projekte",
        contact_h2:"Lass uns vernetzen",
        contact_lede:"Verfügbar Q2 2026 für Werkstudentenstellen — Backend, Frontend, Data Engineering, Analytics, Datenbanken, iOS, Simulation oder jeder Tech-Bereich. Hybrid oder Remote, Deutschland. Schnellste Antwort: E-Mail.",
        ct_email:"E-Mail", ct_linkedin:"LinkedIn", ct_github:"GitHub",
        cf_name:"Dein Name", cf_email:"Deine E-Mail", cf_msg:"Nachricht",
        btn_send:"Nachricht senden",
        live: "Live-Projekt",
        details: "Details",
        cf_ok: "Nachricht gesendet. Ich melde mich bald.",
        cf_err: "Etwas ist schiefgelaufen — bitte direkt per E-Mail.",
        heroChips: ["C#", "SQL", "Python", "Swift", "SwiftUI", "Xcode", "JavaScript", "GitHub", "Unity 3D", "Blender"],
        skillsGroups: [
            { category: "3D & Simulation",
              proofs: [
                  { name: "Unity 3D", note: "7-phasige CO₂-Abscheidungs-Simulation", href: "#project-01" },
                  { name: "C# (Unity)", note: "Modulare Manager-Architektur über alle Phasen", href: "#project-01" },
                  { name: "TextMeshPro / URP", note: "Custom In-Engine-UI für Parameter-Slider", href: "#project-01" },
              ],
              chips: ["Unity 3D", "C#", "TextMeshPro", "URP", "3D-Modellierung", "Simulationsdesign"] },
            { category: "Backend & Programmierung",
              proofs: [
                  { name: "Python", note: "Datenaufbereitung + Ad-hoc-Pipelines (Analytik-Projekte)", href: "#project-05" },
                  { name: "SQL", note: "OVGU Datenbankkonzepte + Analytik-Coursework", href: "#education" },
                  { name: "Swift / SwiftUI", note: "StockWatch iOS-App, MVVM + async/await", href: "https://github.com/hashwanthghanta/stockwatch-ios" },
                  { name: "JavaScript", note: "Dieses Portfolio — Vanilla JS, kein Framework", href: "https://github.com/hashwanthghanta/hashwanthghanta.github.io" },
              ],
              chips: ["Python", "SQL", "JavaScript", "Swift", "SwiftUI", "SwiftUX", "C (Arduino)"] },
            { category: "Werkzeuge & Plattformen",
              proofs: [
                  { name: "Git / GitHub", note: "Öffentliche Repos für Portfolio + StockWatch", href: "https://github.com/hashwanthghanta" },
                  { name: "Arduino / Raspberry Pi", note: "IoT-Helm + Ambulanz-Vorrang-Controller", href: "#project-03" },
              ],
              chips: ["Git", "GitHub", "Jira", "SAP", "Arduino", "Raspberry Pi"] },
            { category: "Aktuell im Aufbau (2025–26)",
              proofs: [
                  { name: "LLMs / Hugging Face", note: "Baue eine kleine RAG-Demo über meine eigenen Projekte", href: "#projects" },
                  { name: "Prompt Engineering", note: "Täglich im Einsatz für Pair-Programming, Code-Reviews und Refactorings", href: "#projects" },
              ],
              chips: ["LLMs", "Hugging Face", "Prompt Engineering", "Transformers", "KI/ML-Konzepte"] },
            { category: "Bearbeitung & Visualisierung",
              proofs: [
                  { name: "Premiere Pro", note: "Schnitt des CO₂-Simulation-Walkthroughs", href: "#project-01" },
                  { name: "Blender", note: "Sechs ingenieurgenaue 3D-Anlagenkomponenten modelliert", href: "#project-01" },
              ],
              chips: ["Adobe", "Videography", "Animation", "Farbkorrektur", "3D-Modellierung"] },
            { category: "Daten & Analytik",
              proofs: [
                  { name: "Power BI", note: "Tata Datenvisualisierungs-Zertifizierungs-Dashboards", href: "#project-05" },
                  { name: "Excel", note: "Microsoft Business Analysis + Finanzmodellierung", href: "#project-05" },
              ],
              chips: ["Power BI", "Excel", "Datenvisualisierung", "Business Analytics"] },
        ],
        track: [
            { date: "2025 – Heute", role: "Simulations- & Laborprojekte", org: "OVGU Magdeburg · Digital Engineering",
              body: "Entwicklung von Unity-Simulationen, C#-Architektur und interaktiven UI-Workflows in Labor- und Modulprojekten." },
            { date: "2025 – Heute", role: "Webentwicklung — Portfolio & Case Studies", org: "Eigenes Projekt",
              body: "Konzeption und Umsetzung eines zweisprachigen Portfolios mit Fokus auf Nutzer-UX, Accessibility und Performance." },
            { date: "2024", role: "Ehrenamtlicher Leiter — VITOPIA 2024", org: "Jährliches Kulturfestival der VIT-AP Universität, Indien",
              body: "Organisation des größten jährlichen Uni-Events mit über 1.000 Teilnehmern, darunter Studierende und Gastauftritte. Verantwortlich für Logistik, Studierendenteams, Veranstaltungsplanung und Live-Aktivitäten." },
        ],
        education: [
            { iconKey: "grad", degree: "M.Sc. Digital Engineering", period: "April 2025 – Heute",
              detail: "<strong>OVGU, Magdeburg, Deutschland</strong>",
              focusAreasLabel: "Schwerpunkte",
              focusAreas: ["Digitale Systeme", "Simulation", "Software-Engineering", "Data Science"],
              subjectsLabel: "Lehrveranstaltungen",
              subjects: [
                  { name: "DE-Visualisierungsprojekt", focus: true },
                  { name: "Datenbankkonzepte" },
                  { name: "Data Mining" },
                  { name: "KI-gestützte Entscheidungsunterstützung" },
                  { name: "Einführung in die Informatik" },
              ] },
            { iconKey: "zap", degree: "B.Tech Elektrotechnik & Kommunikation", period: "2020 – 2024",
              detail: "<strong>VIT-AP Universität, Indien</strong><br>CGPA 7,72 / 10,0",
              focusAreasLabel: "Schwerpunkte",
              focusAreas: ["IoT", "Eingebettete Systeme", "Drahtlose Kommunikation"] },
            { iconKey: "award", degree: "Zertifizierungen", period: "",
              badges: ["Datenvisualisierung – Tata","Business Analysis – Microsoft","Business Analytics – Coursera","IoT Cloud Computing – Coursera","IoT Boards Programmierung – Coursera","Projektmanagement – Coursera","Power BI Workshop"] },
        ],
        services: [
            { name: "Software- & Backend-Entwicklung",       desc: "Saubere objektorientierte Programmierung (OOP) in C# und Swift, robuste Backend-Architektur, Datenbankintegration (SQL) und optimierte Logikimplementierung." },
            { name: "iOS- & SwiftUI-Entwicklung",    desc: "Native iOS-Apps in SwiftUI mit MVVM, async/await-Networking, interaktiven Swift Charts und vollständiger Englisch- + Deutsch-Lokalisierung." },
            { name: "Datenvisualisierung & Analytik",desc: "Power-BI-Dashboards, Excel-Modelle und Python-Pipelines, die Betriebsdaten in klare KPIs, trends und Entscheidungsgrundlagen verwandeln." },
            { name: "IoT & Embedded Systems",        desc: "Arduino- und Mikrocontroller-Systeme für sicherheitskritische Anwendungen — Smart-Helme, Ambulanz-Vorrang, Ultraschall-Blindzonen-Erkennung." },
            { name: "Web- & Markendesign",           desc: "Zweisprachige Portfolios und Case-Study-Seiten mit zugänglichem Markup, performance-first UI und klarer visueller Identität." },
        ],
        projects: [
            {
                num: "01",
                cat: "Hervorgehoben · Unity 3D + Blender",
                name: "Post-Combustion CO₂-Abscheidungs-Simulation",
                period: "2025 – 2026",
                desc: "Fünfköpfiges OVGU-Magdeburg-Teamprojekt zur Simulation der industriellen Post-Combustion-CO₂-Abscheidung für ein 1000-MW-Referenzkraftwerk. Meine Rolle: Unity- & Blender-Entwickler. Sechs ingenieurgenaue 3D-Modelle in Blender 4.x, eine siebenphasige Unity-Coroutine in C#, zwei Live-Temperatur-Slider steuern die Partikelsysteme und den Effizienz-Graphen.",
                highlights: [
                    "5-Personen-Zusammenarbeit zwischen Digital- und Verfahrenstechnik an der OVGU Magdeburg",
                    "Zwei Live-Temperatur-Slider — Absorber 0–65°C und Stripper 75–125°C — steuern Partikelfarbe, -dichte und Effizienz-Graph in Echtzeit",
                    "Sechs ingenieurgenaue 3D-Modelle (Absorber, Stripper, Reboiler, Wärmetauscher, Kompressor, CO₂-Tank) in Blender 4.x modelliert, via FBX nach Unity exportiert",
                    "11 C#-Skripte nach Singleton- + partiellem ECS-Muster; Überhitzungs-Watchdog stoppt bei 125°C automatisch",
                    "Live spielbar auf Unity Play — ohne Installation",
                ],
                learned: "Apply Transform beim FBX-Export ist Pflicht — ohne diese Option landet Blenders Z-up-Welt in Unitys Y-up-Szene um 90° rotiert und im Maßstab 1/100. Eine Checkbox hat uns eine Woche Pipeline-Debugging erspart.",
                tags: ["Unity 2022 LTS", "C#", "Blender 4.x", "TextMeshPro", "UI Toolkit", "FBX-Pipeline", "Simulation"],
                url:  "https://play.unity.com/en/games/30f22392-532c-41e1-b925-6191a9ea99c2/post-combustion-co-carbon-capture",
                urlLabel: "Live-Demo öffnen",
                caseStudy: "projects/co2-simulation-de.html",
                caseStudyLabel: "Case Study lesen",
                img1: "Images/co2-simulation.gif",
                img2: "Images/co2-preview.jpg",
            },
            {
                num: "02",
                cat: "Open Source · iOS · SwiftUI",
                name: "StockWatch — SwiftUI-Watchlist für iOS",
                period: "2026",
                desc: "Native iOS-Watchlist-App, inspiriert von Scalable Capital. Live-Kurse von Yahoo Finance, 55+ Ticker aus US-, deutschen (Xetra), britischen, Schweizer und dänischen Börsen, Listen- + Grid-Layout, interaktive Swift-Charts-Detailansicht mit sieben Zeiträumen, symbolbezogene News, EN/DE-Sprachumschalter zur Laufzeit, Hell/Dunkel/System-Theming.",
                highlights: [
                    "Interaktive Swift-Charts-Detailansicht zum Scrubbing von Schlusskurs und Datum",
                    "MVVM mit @MainActor @Observable, Protokoll-basierte DI, async/await + URLSession",
                    "Sprachumschalter Englisch / Deutsch zur Laufzeit über Bundle-Swizzling",
                    "XCTest-Suite deckt Persistenz, Refresh-Übergänge und Prozent-Mathematik ab",
                ],
                learned: "Protokoll-basierte DI + @MainActor @Observable machten die XCTest-Suite trivial — ich konnte einen Fake-Yahoo-Client in das ViewModel einsetzen, ohne den Produktionscode zu berühren.",
                tags: ["Swift", "SwiftUI", "Swift Charts", "async/await", "MVVM", "XCTest", "iOS 17+"],
                url:  "https://github.com/hashwanthghanta/stockwatch-ios",
                urlLabel: "Auf GitHub ansehen",
                caseStudy: "projects/stockwatch-de.html",
                caseStudyLabel: "Case Study lesen",
                img1: "Images/stockwatch-thumb-sm.jpg",
                img2: "Images/v6_grid_dark-sm.jpg",
            },
            {
                num: "03",
                cat: "IoT · Arduino",
                name: "IoT Smart-Helm & Fahrradsicherheitssystem",
                period: "2024",
                desc: "GPS- und Alkoholsensor-ausgestatteter Smart-Helm zur Erkennung unsicherer Fahrbedingungen und automatischen Alarmierung von Notfallkontakten. Konzipiert zur Reduzierung von Motorradunfällen durch Echtzeit-Überwachung.",
                highlights: [
                    "GPS-Modul + Alkoholsensor auf Arduino-Mikrocontroller",
                    "Automatische Notfall-Alarmierung bei unsicherer Bedingung",
                    "Feldgetestete Wearable-Bauform",
                ],
                learned: "Reine Software-Sperren sind Theater — die Zündung bleibt nur blockiert, weil das Relais physisch in Reihe mit dem Anlasser hängt. Den MQ-3 im Firmware-Setup kalibrieren, nicht erst am Werktisch, sonst scheitert die erste Demo.",
                tags: ["NodeMCU", "ATmega328P", "FSR", "MQ-3", "GSM", "GPS", "Embedded C"],
                svg: "iot_helmet",
                caseStudy: "projects/iot-helmet-de.html",
                caseStudyLabel: "Case Study lesen",
            },
            {
                num: "04",
                cat: "IoT · Embedded · B.Tech",
                name: "IoT-Sicherheitssysteme — Verkehr & Fahrzeug",
                period: "2022 – 2023",
                desc: "Zwei eingebettete Systemprojekte aus dem B.Tech-Studium: ein Kreuzungs-Controller, der Rettungswagen Vorrang gibt, und ein Ultraschall-Toter-Winkel-Detektor für Fahrzeuge. Beides auf Arduino- und Mikrocontroller-Plattformen in Embedded C umgesetzt.",
                highlights: [
                    "Kreuzungs-Controller mit Ambulanz-Vorrang — RF + Mikrocontroller",
                    "Ultraschall-Toter-Winkel-Detektor mit akustischer/visueller Fahrerwarnung",
                    "Embedded C auf Arduino-Hardware",
                ],
                learned: "Zwei Sicherheitssysteme, eine Lektion: Ein Alarm, den niemand hört, ist kein Alarm. Den Ton des Toter-Winkel-Detektors musste ich am Motorgeräusch ausrichten — danach designe ich Feedback fürs reale Umfeld, nicht für die Werkbank.",
                tags: ["IoT", "Arduino", "Sensoren", "Embedded C"],
                svg: "iot_safety",
            },
            {
                num: "05",
                cat: "Data · Analytik · BI",
                name: "Datenanalyse & Business-Intelligence-Dashboards",
                period: "2023 – 2024",
                desc: "Power-BI-Dashboards und Excel-Modelle für Geschäftsdatenanalysen im Rahmen von Zertifizierungsprogrammen mit Tata und Microsoft. Datenvisualisierung zur klaren Darstellung von KPIs, Trends und Betriebskennzahlen für nicht-technische Stakeholder.",
                highlights: [
                    "Power-BI-Dashboards übersetzen Betriebsdaten in KPI-Sichten",
                    "Excel-Finanz-/Forecasting-Modelle mit Named-Range-Refactoring",
                    "Python-Pipelines für Datenaufbereitung und Ad-hoc-Analyse",
                ],
                learned: "Nicht-technische Stakeholder lesen Dashboards wie Entwickler einen Stacktrace — von oben nach unten, auf der Suche nach der einen Zahl, die falsch ist. Ich designe Dashboards seitdem mit der Kernkennzahl zuerst, Drill-down danach.",
                tags: ["Power BI", "Excel", "Datenvisualisierung", "Business Analytics", "Python"],
                svg: "analytics",
            },
        ],
    },
};
